### ISSUE TITLE
Mention SNS to SQS raw messages in the docs?

### ISSUE THREAD

**Issue by gclitheroe** [mulesoft/sqs-connector#13]
Hi,

It used to be that when messages where sent via SNS to SQS (fanout) they used to arrive wrapped in JSON and the SQS connector had to do a little more work to unpack the message from the JSON.  It also meant that an SQS connector had to have some upstream knowledge of the message routing (not great).

It's been possible for a while to use a raw message subscription for SNS to SQS which sends the message from SNS to SQS not wrapped in JSON.  http://docs.aws.amazon.com/sns/latest/dg/large-payload-raw-message.html

Worth adding to your docs somewhere?

**Comment by karthikanantha** [comment]
Based on the above discussion, moving the issue to SNS Connector.
