### ISSUE TITLE
Support proxy settings

### ISSUE THREAD

**Issue by vromero** [mulesoft/sqs-connector#24]
From stackoverflow's: http://stackoverflow.com/questions/26843172/mulesoft-proxy-settings-not-working-for-amazon-sqs

SQS connector doesn't honor proxy settings: http.proxyHost=rb-proxy-apac.bosch.com -Dhttp.proxyPort=8080 -Dhttp.proxyUser=prd5kor -Dhttp.proxyPassword=asdf

**Comment by karthikanantha** [comment]
The proxy support settings have been added to the connector global configuration element in the upcoming v3.0.0 release of the connector.
