### ISSUE TITLE
SQS Connector Requires Message Attributes

### ISSUE THREAD

**Issue by monomidev** [mulesoft/sqs-connector#56]
Even though you can set Message Attributes to None and AWS does not requires Message Attributes with an SQS Send Message, the Amazon SQS Connector requires message attributes and passes them automatically.

I am using the following configuration per the documentation:

```xml
<sub-flow name="sqsSendMessage">
        <object-to-string-transformer doc:name="Object to String"/>
        <set-variable variableName="SQSMessage" value="#[message.payload]" doc:name="SQSMessage"/>
        <scripting:component doc:name="Groovy">
            <scripting:script engine="Groovy"><![CDATA[import org.mule.modules.sqs.model.MessageAttributeValue;
Map<String, MessageAttributeValue> messageAttributes = new HashMap<String, MessageAttributeValue>();
messageAttributes.put("AccountId", new MessageAttributeValue(null,"000123456", "String"));
messageAttributes.put("NumberId", new MessageAttributeValue(null,"230.000000000000000001","Number"));
return messageAttributes;]]></scripting:script>
        </scripting:component>
        <sqs:send-message config-ref="SQS" message="#[flowVars.SQSMessage]" queueUrl="******" doc:name="Amazon SQS"/>
        <json:object-to-json-transformer doc:name="Object to JSON"/>
    </sub-flow>
```

The above xml results in a message in SQS with the Attributes AccountId and NumberId.  I have Message Attributes set to "None" in the SQS Connector.  You can see this in the above XML as there is no config item within SQS.  The SQS Send Message fails if I do not provide the payload as a MessageAttribute into the connector, which I can understand but in this case, MessageAttributes are still set even though I specified None in the connector.

Amazon SQS does not requires Message Attributes, so I think the fix should be to not require a MessageAttributes payload going into the connector, at the very least respect the "None" configuration of the connector.

*Note, I am new to SQS but the documentation I have read shows MessageAttributes are not required.  I am able to create a message without attributes in SQS going direct to web services.  I see it as inefficient to require me having a groovy script to build an empty map just to send a message.

**Comment by karthikanantha** [comment]
Hi Lance,

As you rightly said, Amazon SQS Message Attributes is optional with an SQS Send Message and the connector honors the same. The issue is with Object Builder not able to generate the XML properly. When you want to set the Message Attributes to None, instead of 
```xml
<sqs:send-message config-ref="SQS" message="#[flowVars.SQSMessage]" queueUrl="******" doc:name="Amazon SQS"/>
```
manually set it as 
```xml
<sqs:send-message config-ref="SQS" message="#[flowVars.SQSMessage]" queueUrl="******" doc:name="Amazon SQS">
 <sqs:message-attributes />
</sqs:send-message>
```
This would solve your problem.

when you set it as 
```xml
<sqs:send-message config-ref="SQS" message="#[flowVars.SQSMessage]" queueUrl="******" doc:name="Amazon SQS"/>
```
this would default to 
```xml
<sqs:send-message config-ref="SQS" message="#[flowVars.SQSMessage]" queueUrl="******" doc:name="Amazon SQS">
    <sqs:message-attributes ref="#[payload]"/>
</sqs:send-message>
```
 and thats why its picking up the message attributes.

**Comment by monomidev** [comment]
Thank you!  I didn't event think of that.  That works great.
